# Generated by Django 4.1.2 on 2022-10-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="post",
        ),
    ]
